#ifndef SPA_SRC_SPA_SRC_SP_ARITHMETICOPERATORTYPE_H_
#define SPA_SRC_SPA_SRC_SP_ARITHMETICOPERATORTYPE_H_

enum ArithmeticOperatorType {
  PLUS,
  MINUS,
  DIV,
  MULTIPLY,
  MOD
};

#endif //SPA_SRC_SPA_SRC_SP_ARITHMETICOPERATORTYPE_H_
