#ifndef SPA_SRC_SPA_SRC_SP_CONDITIONALOPERATORTYPE_H_
#define SPA_SRC_SPA_SRC_SP_CONDITIONALOPERATORTYPE_H_

enum ConditionalOperatorType {
  AND,
  OR,
  NOT,
};

#endif //SPA_SRC_SPA_SRC_SP_CONDITIONALOPERATORTYPE_H_
