#ifndef SPA_SRC_SPA_SRC_SP_PUNCTUATIONTYPE_H_
#define SPA_SRC_SPA_SRC_SP_PUNCTUATIONTYPE_H_

enum PunctuationType {
  LEFT_PARENTHESIS,
  RIGHT_PARENTHESIS,
  LEFT_BRACE,
  RIGHT_BRACE,
  SEMICOLON,
  DOUBLE_QUOTE,
  SINGLE_EQUAL
};

#endif //SPA_SRC_SPA_SRC_SP_PUNCTUATIONTYPE_H_
