#ifndef SPA_SRC_SPA_SRC_SP_RELATIONALOPERATORTYPE_H_
#define SPA_SRC_SPA_SRC_SP_RELATIONALOPERATORTYPE_H_

enum RelationalOperatorType {
  LT,
  LTE,
  GT,
  GTE,
  DOUBLE_EQUALS,
  NE,
};

#endif //SPA_SRC_SPA_SRC_SP_RELATIONALOPERATORTYPE_H_
