name: Continuous Integration

on:
  push:
    branches:
      - master
      - "milestone[1-3]"
  pull_request:
    branches:
      - master
      - "milestone[1-3]"

env:
  BUILD_TYPE: Release

jobs:
  build_windows:
    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true

    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
        with:
          architecture: 'x64'
      - name: Build Project
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/Team02/Code02
          mkdir build
          cd build
          cmake -A x64 ..
          cmake --build . --target unit_testing --config Release
          cmake --build . --target integration_testing --config Release
          cmake --build . --target autotester --config Release
          cmake --build . --target spa_benchmarks --config Release
          cd ../..

      - name: Unit Testing
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/Team02/Code02/build/src/unit_testing/Release
          ./unit_testing.exe

      - name: Integration Testing
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/Team02/Code02/build/src/integration_testing/Release
          ./integration_testing.exe

      - name: Running System Tests
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/Team02/Tests02
          python RunTests.py False

  build_macos:
    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/Team02/Code02/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Unit Testing
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ./src/unit_testing/unit_testing

      - name: Integration Testing
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ./src/integration_testing/integration_testing

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Running System Tests
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: python3 $GITHUB_WORKSPACE/Team02/Tests02/RunTests.py False
