name: System Testing

on:
  push:
    branches:
      - master
      - "milestone[1-3]"
  pull_request:
    branches:
      - master
      - "milestone[1-3]"

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Building Autotester
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/Team02/Code02
          mkdir build
          cd build
          cmake -A x64 ..
          cmake --build . --target autotester --config Release
          cd ../..

      - name: Running System Tests
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/Team02/Tests02
          python RunTests.py False
